; PlatformIO Project Configuration File
; FlightRadarCYD - Live Aircraft Radar

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    moononournation/GFX Library for Arduino
    bblanchon/ArduinoJson@^6
